stages: # defines execution order so jobs don't all start simultaneously
    - doc
    - build

render_documentation:
  stage: doc
  script:
    - doxygen # generate documentation
    - cp -R doc/html/* /var/www/html/doxygen/ # Copy to apache dir

build_app:
  stage: build
  script:
    - cp /home/ubuntu/.processing/preferences.txt /home/gitlab-runner/.processing/preferences.txt # Keep preferences (e.g. Sketchbook path) up to date so that libraries found
    - processing-java --sketch=`readlink -f src/Lsim/` --build # build using absolute path
