name: CI
# Controls when the workflow will run
on:
  push:
    branches: [doxygen-dev]
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_on_macos:
    runs-on: macos-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          path: Lsim

      # Install dependencies
      - name: Download and install Processing 4 beta
        run: |
          wget -q https://github.com/processing/processing4/releases/download/processing-1282-4.0b7/processing-4.0b7-macos-x64.zip -O ~/Downloads/Processing.zip
          tar -xf ~/Downloads/Processing.zip -C /Applications/
          ls -al $GITHUB_WORKSPACE/Lsim
          chmod +x $GITHUB_WORKSPACE/Lsim/.github/workflows/processing-java
      
      - name: Install UDP lib
        run: |
          wget -d --header="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0" --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" --header="Accept-Encoding: gzip, deflate, br" --header="Host: www.ubaa.net" --header="Connection: keep-alive" https://www.ubaa.net/shared/processing/udp/udp.zip
          unzip -q udp.zip
          mkdir Lsim/src/Lsim/code && cp udp/library/udp.jar "$_"
      
      # Export for different platforms
      - name: macos-x86_64 export 
        run: |
          $GITHUB_WORKSPACE/Lsim/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Lsim/src/Lsim --output=$GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_macos-x86_64 --variant=macos-x86_64 --export
          zip -rq Lsim_${GITHUB_REF#refs/tags/}_macos-x86_64.zip Lsim_${GITHUB_REF#refs/tags/}_macos-x86_64/ -x "Lsim_${GITHUB_REF#refs/tags/}_macos-x86_64/source/*"
      - name: macos-aarch64 export
        run: |
          $GITHUB_WORKSPACE/Lsim/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Lsim/src/Lsim --output=$GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_macos-aarch64 --variant=macos-aarch64 --export
          zip -rq Lsim_${GITHUB_REF#refs/tags/}_macos-aarch64.zip Lsim_${GITHUB_REF#refs/tags/}_macos-aarch64/ -x "Lsim_${GITHUB_REF#refs/tags/}_macos-aarch64/source/*"
      - name: linux-amd64 export
        run: |
          $GITHUB_WORKSPACE/Lsim/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Lsim/src/Lsim --output=$GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_linux-amd64 --variant=linux-amd64 --export
          zip -rq Lsim_${GITHUB_REF#refs/tags/}_linux-amd64.zip Lsim_${GITHUB_REF#refs/tags/}_linux-amd64/ -x "Lsim_${GITHUB_REF#refs/tags/}_linux-amd64/source/*"
      - name: linux-arm export
        run: |
          $GITHUB_WORKSPACE/Lsim/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Lsim/src/Lsim --output=$GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_linux-arm --variant=linux-arm --export
          zip -rq Lsim_${GITHUB_REF#refs/tags/}_linux-arm.zip Lsim_${GITHUB_REF#refs/tags/}_linux-arm/ -x "Lsim_${GITHUB_REF#refs/tags/}_linux-arm/source/*"
      - name: linux-aarch64 export
        run: |
          $GITHUB_WORKSPACE/Lsim/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Lsim/src/Lsim --output=$GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_linux-aarch64 --variant=linux-aarch64 --export
          zip -rq Lsim_${GITHUB_REF#refs/tags/}_linux-aarch64.zip Lsim_${GITHUB_REF#refs/tags/}_linux-aarch64/ -x "Lsim_${GITHUB_REF#refs/tags/}_linux-aarch64/source/*"

      # Upload assets to created release
      - name: Upload release assets 
        run: > 
          cd $GITHUB_WORKSPACE/Lsim

          gh release upload ${GITHUB_REF#refs/tags/} 
          $GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_macos-x86_64.zip
          $GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_macos-aarch64.zip
          $GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_linux-amd64.zip
          $GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_linux-arm.zip
          $GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_linux-aarch64.zip
          --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This workflow contains a single job called "build"
  build_on_ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          path: Lsim 

      - name: Download and install Processing 3
        run: |
          wget https://github.com/processing/processing/releases/download/processing-0270-3.5.4/processing-3.5.4-linux64.tgz
          tar zxvf processing-3.5.4-linux64.tgz
          cd processing-3.5.4
          ./install.sh
      
      - name: Install UDP lib
        run: |
          wget -d --header="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0" --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" --header="Accept-Encoding: gzip, deflate, br" --header="Host: www.ubaa.net" --header="Connection: keep-alive" https://www.ubaa.net/shared/processing/udp/udp.zip
          unzip -q udp.zip
          mkdir Lsim/src/Lsim/code && cp udp/library/udp.jar "$_"
      
      - name: Install 32bit libs
        run: sudo apt update && sudo apt install lib32z1
      
      - name: windows export
        run: |
          $GITHUB_WORKSPACE/processing-3.5.4/processing-java --sketch=$GITHUB_WORKSPACE/Lsim/src/Lsim --output=$GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_windows --platform=windows --export;
          zip -rq Lsim_${GITHUB_REF#refs/tags/}_windows.zip Lsim_${GITHUB_REF#refs/tags/}_windows/ -x "Lsim_${GITHUB_REF#refs/tags/}_windows/source/*"
      
      # Upload assets to created release
      - name: Upload release assets 
        run: > 
          cd $GITHUB_WORKSPACE/Lsim

          gh release upload ${GITHUB_REF#refs/tags/} 
          $GITHUB_WORKSPACE/Lsim_${GITHUB_REF#refs/tags/}_windows.zip
          --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
